# navigator
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# Sidebar
sidebar: right

# sidebar widget
widgets:
- nav
- toc
- about
- friends

# layout
# excerpt_link inner
excerpt_link: Read More

# friend link
friends:
  name: MyFriends
  link: https://hexo.io/ 

# article
# valine comment
comment:
  enable: false
  appId: 
  appKey: 

# code highlight
# option: agate tomorrow tomorrow-night
# you can add your code scheme into hexo-theme-bubblegum/source/css/_highlight folder
highlight: agate

# scheme
# option: light dark auto
scheme: auto

# about widget 
# wirte your social link
social:
  qq: 
  wechat:
  github: 
  bilibili: 

# write your profile image link
Profile: 
  url: 

# footer
# beian
beian:
  ICP_number: 
  wangan_number: 

# baidu analyze
baidu_Analyze: 
  id: 

# cdn link
cdn:
  valine: https://cdn.jsdelivr.net/npm/valine@1.4.14/dist/Valine.min.js
  animate: https://cdn.bootcdn.net/ajax/libs/animate.css/4.1.1/animate.min.css
  rasterizehtml: https://cdn.bootcdn.net/ajax/libs/rasterizehtml/1.3.0/rasterizeHTML.allinone.js
